### GET ALL PERSONS
GET http://localhost:3001/api/blogs

### POST request
POST  http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "Title of blog",
    "author": "Linares",
    "url": "url_of_blog"
}
