### GET ALL PERSONS
GET http://localhost:3001/api/blogs

### POST request
POST  http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "Title of blog",
    "author": "Linares",
    "url": "url_of_blog"
}

### POST request
PUT  http://localhost:3001/api/blogs/65df75da0dadb7e97dc9439a
Content-Type: application/json

{
	"title": "EditedTitle",
    "url": "editedUrl",
    "likes": 123
}