### GET ALL PERSONS
GET http://localhost:3001/api/blogs

### POST request
POST  http://localhost:3001/api/blogs
Content-Type: application/json

{
	"title": "Title of blog 2",
    "author": "Fernando Alonso",
    "url": "url_of_blog2",
    "likes": 4,
    "userId": "65e37e1bcbfffbf0dc46e8b1"
}

### POST request
PUT  http://localhost:3001/api/blogs/dasfgcdasfc
Content-Type: application/json

{
	"title": "EditedTitle",
    "url": "editedUrl",
    "likes": 123
}